ENT.Type 			= "anim"
ENT.Base 			= "base_gmodentity"
ENT.PrintName		= "Health Meter"
ENT.Author			= "LightDemon -Based off Paradukes origanl idea"
ENT.Category 		= "Gcombat"
ENT.Purpose			= "displays props gcombat health"  
ENT.Instructions	= "wire a scren to it and point it at someting."  
ENT.Contact			= "LightDemon@fullsail.edu"  
ENT.Spawnable		= true
ENT.AdminSpawnable	= true
