ENT.Type 			= "anim"
ENT.Base 			= "base_gmodentity"
ENT.PrintName		= "Ordinance Rack"
ENT.Author			= "Paradukes"

ENT.Spawnable		= true
ENT.AdminSpawnable	= true
ENT.Owner			= nil
ENT.SPL			= nil
ENT.CDown			= 0
ENT.MWidth			= 60
ENT.OWidth			= 0
ENT.AWidth			= 60
ENT.S1			= nil
ENT.S2			= nil
ENT.S3			= nil
ENT.S4			= nil
ENT.S5			= nil
ENT.S6			= nil
ENT.S7			= nil
ENT.S8			= nil
ENT.S9			= nil
ENT.S10			= nil
ENT.S11			= nil
ENT.S12			= nil
ENT.S13			= nil
ENT.S14			= nil
ENT.S15			= nil