ENT.Type 			= "anim"
ENT.Base 			= "base_gmodentity"
ENT.PrintName		= "O-Rackable AAM"
ENT.Author			= "MadMoe"

ENT.Spawnable		= true
ENT.AdminSpawnable	= true
ENT.Owner			= nil
ENT.SPL			= nil
ENT.Exploded		= false
ENT.PreLaunch 		= false
ENT.BLShell			= false
ENT.Fired			= false
ENT.RWidth			= 8
ENT.ORackable		= true
ENT.Horiz			= false
ENT.DWidth			= 5
ENT.Warhead			= ""
ENT.WHMk2			= true